### ISSUE TITLE
Error in make rip

### ISSUE THREAD

**Issue by Readmit0** [everything8215/ff6#3]
I'm getting an error with the Final Fantasy 3 SNES disassembly. If I run make rip with a vanilla rom in the vanilla folder, I get this error. I'm not sure why, because I have all of the dependencies installed and the make rip almost works all the way through.

![image](https://github.com/user-attachments/assets/ffa521f6-0003-4da1-b95a-92cc9ba1f2ab)

**Comment by everything8215** [comment]
This should now be [fixed](https://github.com/everything8215/ff6/commit/cad027a60c07b96b318fcd32d710fca693b36b6b). It was trying to find asset files for the Japanese version but you only had the English ROM in the `vanilla` folder. It will now ignore versions that haven't been ripped. Thanks for reporting this.
