### ISSUE TITLE
Cant compile the project

### ISSUE THREAD

**Issue by Marcelo20XX** [everything8215/ff6#4]
After installing the required dependencies and after ripping the assets from a supported vanilla rom, I cant seem to compile the project, whenever I run the command "make ff6-en1" I got the following errors:

`$ make ff6-en1
python3 tools/fix_dlg.py split en
python3 tools/encode_text.py src/text/dlg1_en.json
python3 tools/encode_text.py src/text/dlg2_en.json
python3 tools/fix_dlg.py combine en
ca65 -g -I include -D LANG_EN=1 -D ROM_VERSION=1 -l obj/field_en1.lst src/field/field_main.asm -o obj/field_en1.o
src/field/entrance.asm:208: Error: Constant expression expected
include/macros.inc:450: Note: Macro was defined here
src/field/entrance.asm:385: Error: Constant expression expected
include/macros.inc:450: Note: Macro was defined here
src/field/player.asm:911: Error: Constant expression expected
include/macros.inc:450: Note: Macro was defined here
make: *** [Makefile:96: obj/field_en1.o] Error 1
`

I tried building in Windows 10 using a MSYS Shell and using Linux Ubuntu command terminal, in both cases the errors are the same...

**Comment by everything8215** [comment]
It looks like something went wrong when it ripped assets from the original ROM. You can try running `make distclean` to delete all assets followed by `make rip` to rip them again. If that doesn’t fix the errors, open `include/field/short_entrance.inc` and let me know if the symbol `ARRAY_LENGTH` is defined somewhere.

**Comment by Marcelo20XX** [comment]
Thanks it worked, turns out to be that the "make rip" command was failing after the initial assets extraction for some reason in my MSyS2 shell, probably because a conflicting python3 installation, but after running the commands on Ubuntu I had zero issues and the project compiled, thanks again!
